apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    app: appointment
spec:
  type: LoadBalancer
  selector:
    app: appointment
  ports:
    - port: 80        # external port (ELB will listen on 80)
      targetPort: 3001 # forwards traffic to container port
      protocol: TCP
