apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    app: appointment
spec:
  type: LoadBalancer
  selector:
    app: appointment
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 3001  # Container port
