apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    app: patient
spec:
  type: LoadBalancer
  selector:
    app: patient
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 3000  # Container port
