name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: 666802050306.dkr.ecr.us-east-1.amazonaws.com/semo
      CLUSTER_NAME: sumanth-new

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4️⃣ Set commit SHA for image tags
      - name: Set commit SHA
        run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      # 5️⃣ Build & push Appointment image
      - name: Build & Push Appointment Image
        run: |
          IMAGE_URI="666802050306.dkr.ecr.us-east-1.amazonaws.com/semo:appointment-${COMMIT_SHA}"
          docker build -t $IMAGE_URI ./kubernetes/appointment
          docker push $IMAGE_URI

      # 6️⃣ Build & push Patient image
      - name: Build & Push Patient Image
        run: |
          IMAGE_URI="666802050306.dkr.ecr.us-east-1.amazonaws.com/semo:patient-${COMMIT_SHA}"
          docker build -t $IMAGE_URI ./kubernetes/patient
          docker push $IMAGE_URI

      # 7️⃣ Update kubeconfig
      - name: Update kubeconfig
        run: aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME

      # 8️⃣ Deploy Appointment
      - name: Deploy Appointment
        run: |
          kubectl set image deployment/appointment-deployment appointment-container=666802050306.dkr.ecr.us-east-1.amazonaws.com/semo:appointment-${COMMIT_SHA}
          kubectl rollout status deployment/appointment-deployment
          kubectl apply -f ./kubernetes/appointment/service.yaml

      # 9️⃣ Deploy Patient
      - name: Deploy Patient
        run: |
          kubectl set image deployment/patient-deployment patient-container=666802050306.dkr.ecr.us-east-1.amazonaws.com/semo:patient-${COMMIT_SHA}
          kubectl rollout status deployment/patient-deployment
          kubectl apply -f ./kubernetes/patient/service.yaml
